[project]
name = "January API"
version = "0.0.2"
description = "January's API"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn>=0.30.6",
]

[tool.uv.sources]
fastapi = { workspace = true }
